name: 'dbt_clients_marketing'
version: '0.3.0'

#  profile: 'dbt_clients_marketing'

require-dbt-version: [ ">=1.3.0", "<2.0.0" ]

model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
seed-paths: [ "seeds" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  #  client_name: client

  #  marketing_database:
  #    dev: evidy-dev-data-raw
  #    prod: evidy-prod-data-raw


  #  glami_enabled: true
  #  google_ads_enabled: true
  #  seznam_sklik_enabled: true

seeds:
  +schema: seeds

models:
  dbt_clients_marketing:
    materialized: ephemeral
    bind: false
    sources:
      +schema: marketing_source
      +materialized: view
      base:
        +materialized: ephemeral
    marts:
      +schema: marketing
      +materialized: table
      intermediate:
        +materialized: ephemeral
